### https://terraform-docs.io/user-guide/configuration/
### To generate the output file to partially incorporate in the README.md,
### Execute this command in the Terraform module's code folder:
# terraform-docs -c .terraform-docs.yml .

version: "~> 0.18"

formatter: "markdown document"

recursive:
  enabled: false
  path: modules

sections:
  hide: []
  show: []

output:
  file: README.md
  mode: inject

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: true
  html: true
  indent: 2
  lockfile: false
  read-comments: true
  required: true
  sensitive: true
  type: true
